language: python
sudo: required
python:
- '3.6'
services:
- docker
cache: pip
os: linux
dist: bionic

before_install:
  - bash scripts/run_sgx_simulator.sh
  - mkdir $CERT_PATH
  - docker run -d -p 8545:8545
    --name ganache trufflesuite/ganache-cli:v6.8.1-beta.0
install:
  - sudo apt-get install libudev-dev
  - sudo apt-get install libusb-1.0-0-dev
  - sudo apt-get install python3-dev
  - pip install -e .
  - pip install -e .[dev]

before_script:
  - "flake8 ."

jobs:
  include:
    - stage: test
      script:
        - py.test tests/http_test.py
        - py.test tests/test.py
        - python ./tests/test.py || travis_terminate 1
        - sh -c "while :; do clear; date; sleep 300; done" &
        - pytest -m "not longtest" ./tests/test_dkg.py || travis_terminate 1
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pytest -m "longtest" ./tests/test_dkg.py || travis_terminate 1; fi'
    - stage: deploy
      if: branch IN (develop, beta, stable, master)
      script:
        - export VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./scripts/calculate_version.sh)
        - echo "Version $VERSION"
        - bash ./scripts/build.sh
      before_deploy:
        # Set up git user name and tag this commit
        - (
          test ! $TRAVIS_TAG &&
          git config --local user.name "skale-travis" &&
          git config --local user.email "$GITHUB_EMAIL" &&
          export TRAVIS_TAG=$VERSION &&
          git tag "$TRAVIS_TAG" &&
          git push https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_TAG
          ) || true
      deploy:
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          name: $VERSION @ $(date +'%d.%m.%Y %R')
          on:
            repo: $TRAVIS_REPO_SLUG
            branch: master
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          prerelease: true
          name: $VERSION @ $(date +'%d.%m.%Y %R')
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - develop
              - beta
        - provider: script
          skip_cleanup: true
          script: bash $TRAVIS_BUILD_DIR/scripts/publish.sh
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - master
              - stable
              - develop
              - beta
