version: '3.0'

services:
  grafana:
    container_name: grafanalabs-surrealdb-datasource
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafanalabs-surrealdb-datasource
      - ./provisioning:/etc/grafana/provisioning
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    command: start --user grafana --pass password file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./tmp/data:/data
