---
# vars file for user
user_dependencies:
  - default-jdk
  - libnotify-bin
  - python3-psutil
  - unzip
  - vim
  - vim-gtk3

user_stu_host_key: "stu.cs.jmu.edu ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXS19kf1swKRC9GTTiUDyOzra0sYT+kt6Vxd4Q0H9uw"
