---
# vars file for eclipse
eclipse:
  # Ensure the URL does not specify a mirror and that &r=1 is at the end, which
  # directly links to the file and not the web page with a download button
  url: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-06/R/eclipse-java-2021-06-R-linux-gtk-{{ ansible_architecture }}.tar.gz&r=1'
  url_backup: 'https://download.eclipse.org/technology/epp/downloads/release/2021-06/R/eclipse-java-2021-06-R-linux-gtk-{{ ansible_architecture }}.tar.gz'
  hash:
    x86_64: '615f495abcb3ace8d9c8008d75f74b9bcd5a30cc'
    aarch64: 'd45a1b72be74a34491883a34ea27bd71b14c22cb'
  zip: '{{ global_base_path }}/eclipse.tar.gz'
  install_path: '{{ global_base_path }}/eclipse'

eclipse_remove_mint:
  - eclipse-jdt
  - eclipse-platform
  - eclipse-platform-data
  - eclipse-rcp
