---
# vars file for eclipse
eclipse:  # noqa var-naming[no-role-prefix]
  # Ensure the URL does not specify a mirror and that &r=1 is at the end, which
  # directly links to the file and not the web page with a download button
  url: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2023-12/R/eclipse-java-2023-12-R-linux-gtk-{{ ansible_architecture }}.tar.gz&r=1'
  url_backup: 'https://download.eclipse.org/technology/epp/downloads/release/2023-12/R/eclipse-java-2023-12-R-linux-gtk-{{ ansible_architecture }}.tar.gz'
  hash:
    x86_64: '04a289df397b52bb08e6eb4bd4d2ff93a8120d61'
    aarch64: 'ab34d85d657cd7fae55215b61cf4ed4868b53a4e'
  zip: '{{ common_global_base_path }}/eclipse.tar.gz'
  install_path: '{{ common_global_base_path }}/eclipse'

eclipse_remove_mint:
  - eclipse-jdt
  - eclipse-platform
  - eclipse-platform-data
  - eclipse-rcp
