---
# vars file for eclipse
eclipse:  # noqa var-naming[no-role-prefix]
  # Ensure the URL does not specify a mirror and that &r=1 is at the end, which
  # directly links to the file and not the web page with a download button
  url: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2023-06/R/eclipse-java-2023-06-R-linux-gtk-{{ ansible_architecture }}.tar.gz&r=1'
  url_backup: 'https://download.eclipse.org/technology/epp/downloads/release/2023-06/R/eclipse-java-2023-06-R-linux-gtk-{{ ansible_architecture }}.tar.gz'
  hash:
    x86_64: '8a54f3fb7abb3203559b4db403681a815edc406a'
    aarch64: '958626a64c455c5e1a9e14c44526748ba2ce81d9'
  zip: '{{ common_global_base_path }}/eclipse.tar.gz'
  install_path: '{{ common_global_base_path }}/eclipse'

eclipse_remove_mint:
  - eclipse-jdt
  - eclipse-platform
  - eclipse-platform-data
  - eclipse-rcp
