---
# tasks file for Linux Mint

- name: Update mintupdate package
  ansible.builtin.apt:
    name: "{{ oem_upgrade_pre_mintupdate }}"
    state: latest
- name: Upgrade all installed packages  # noqa no-changed-when
  ansible.builtin.command:
    cmd: /usr/bin/mintupdate-cli -y upgrade
- name: Install oem-config
  ansible.builtin.apt:
    name:
      - oem-config
      - oem-config-gtk
    state: latest

- name: Ensure skeleton desktop directory exists
  ansible.builtin.file:
    path: "{{ oem_skel_desktop_file_path }}"
    state: directory
    mode: "0755"
- name: Copy welcome shortcut to skeleton desktop directory
  ansible.builtin.copy:
    src: welcome-to-vm.desktop
    dest: "{{ oem_skel_desktop_file_path }}/welcome-to-vm.desktop"
    mode: "0644"
- name: Hide the mintwelcome window
  ansible.builtin.file:
    path: "{{ oem_skel_path }}/.linuxmint/mintwelcome"
    mode: "0755"
    state: directory
- name: Hide the mintwelcome window
  ansible.builtin.copy:
    dest: "{{ oem_skel_path }}/.linuxmint/mintwelcome/norun.flag"
    mode: "0664"
    content: ""
    force: no
- name: Copy setup script shortcut to desktop
  ansible.builtin.copy:
    src: "{{ common_wrapper_desktop_file_path }}/jmucs_config.desktop"
    dest: "{{ oem_skel_desktop_file_path }}/jmucs_config.desktop"
    mode: "0755"
- name: Copy dconf config file
  ansible.builtin.copy:
    src: csconfig-mintonly
    dest: /etc/dconf/db/local.d/csconfig-mintonly
    owner: root
    group: root
    mode: "0644"
  notify:
    - Update dconf database
