---
# tasks file for Linux Mint

- name: Create directory for custom MintReport script
  file:
    path: /usr/share/linuxmint/mintreport/reports/001_Run-JMU-CS-Config-Tool
    mode: "0755"
    owner: root
    group: root
    state: directory
- name: Install custom MintReport script
  template:
    src: CustomMintReportInfo.py
    dest: /usr/share/linuxmint/mintreport/reports/001_Run-JMU-CS-Config-Tool/MintReportInfo.py
    mode: "0644"
    owner: root
    group: root

- name: Set Linux Mint mirrors
  template:
    src: mint.j2
    dest: /etc/apt/sources.list.d/official-package-repositories.list
    owner: root
    group: root
    mode: "0644"
  when: "ansible_architecture == 'x86_64'"
