---
# tasks file for programming-langs

- name: Install Ruby packages
  ansible.builtin.apt:
    name: "{{ programming_langs_ruby_packages }}"
    state: latest

- name: Install Haskell packages
  ansible.builtin.apt:
    name: "{{ programming_langs_haskell_packages }}"
    state: latest

- name: Install Prolog packages
  ansible.builtin.apt:
    name: "{{ programming_langs_prolog_packages }}"
    state: latest
