name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test backend
        uses: magefile/mage-action@v3
        with:
          version: latest

      - name: Build backend
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildAll

      - uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: dist/
          retention-days: 1

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check types
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test:ci

      - name: Build frontend
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/
          retention-days: 1
          
    timeout-minutes: 60
